wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1644484143
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      - 13
      - 16
      4: 3.7.10
      5: 0.12.10
      8:
      - 1
      - 5
architecture:
  desc: null
  value: DenseNet121 pretrained
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: 220210_data
epochs:
  desc: null
  value: 50
loss_function:
  desc: null
  value: categorical_crossentropy
memo:
  desc: null
  value: monitorValAccuracy
